### ISSUE TITLE
crashes with illegal component declaration

### ISSUE THREAD

**Issue by schmod** [schmod/babel-plugin-angularjs-annotate#11]
An "illegal" component declaration causes the plugin to crash and exit.  We should tolerate this gracefully. 

```js
angular.module('foo').component({})
```

causes the plugin to exit with:

```
unknown: Cannot set property '$chained' of undefined
```

**Comment by danpantry** [comment]
It doesn't just crash with an illegal declaration, unfortunately. The following code also caused this issue for me (I wrote it out of laziness..)

````javascript
const components = {
  someName: someComponentObject
}

const ngModule = angular.module('components', [])
Object.keys(components).forEach((name) => ngModule.component(name, components[name]))
````

**Comment by schmod** [comment]
@danpantry I've fixed things so your example no longer crashes, but you're definitely going to need to add explicit annotations to that source for it to be annotated.

**Comment by danpantry** [comment]
This example shouldn't need any annotations at all - components cannot be annotated as they are just objects. controllers of components, sure

**Comment by schmod** [comment]
True!  But those controllers are indeed going to need explicit annotations.
