### ISSUE TITLE
Usage instructions in .babelrc are non-standard

### ISSUE THREAD

**Issue by mgol** [schmod/babel-plugin-angularjs-annotate#2]
The README mentions the way to add the plugin to `.babelrc`:
```json
{
  "presets": ["es2015"],
  "plugins": ["path/to/babel-ng-annotate"]
}
```

However, that seems like an anti-pattern; people shouldn't depend on specific paths to the plugin (especially that the `babel-ng-annotate` doesn't match the name of the plugin), they should just use the plugin name as with every other plugin:
```json
{
  "presets": ["es2015"],
  "plugins": ["angularjs-annotate"]
}
```

**Comment by schmod** [comment]
Will fix.  That's a relic from before this was published to NPM 

(Although I'll note that many people _do_ use full paths if their babel configurations, particularly when including modules via `npm link` -- Babel and/or webpack have difficulty resolving modules in that scenario; see https://github.com/babel/babel-loader/issues/149)
