### ISSUE TITLE
Support 'ngInject' string-based annotation

### ISSUE THREAD

**Issue by mgol** [schmod/babel-plugin-angularjs-annotate#3]
The README only mentions implicit annotation or one done via the `/* @ngInject */` comment. The `'ngInject';` string-based annotation should be supported as well:
```js
class svc {
  constructor(dep1){
    'ngInject';
    this.dep1 = dep1;
  }
  method1() {
    this.dep1.doSth();
  }
}
```

**Comment by schmod** [comment]
Do you have a reason for preferring this style?  

I generally haven't seen it used much in the wild, and `@`-prefixed comments seem to be the standard convention for annotating JS sources, and mimic the annotation syntax used in ES6/Java/Python.

**Comment by mgol** [comment]
I guess you're right in that it reminds other tools more.

My preference came from a few things:

1. The fact that I have `'ngInject';` sprinkled all over my projects so migrating to this Babel plugin would require refactoring. 😄 
1. It resembles `"use strict"`, `"use asm"` etc. a little.
1. ng-annotate itself has described this way as the preferred one: https://github.com/olov/ng-annotate#explicit-annotations-with-nginject

**Comment by mgol** [comment]
See also https://github.com/olov/ng-annotate/issues/180#issuecomment-165988194 and https://github.com/olov/ng-annotate/issues/206. I have an impression that quite many people think the `'ngInject';` pragma is the recommended way, some even think other forms are deprecated. :) In some cases it's the only way as some transpilers will lose comments or misplace them.

Adding this way of annotating would increase the compatibility with the original `ng-annotate`.

**Comment by mgol** [comment]
Thanks! :tada:

**Comment by schmod** [comment]
Huh.  I didn't realize that it had emerged as the preference.  

Fortunately, it's also a whole lot easier to implement.

Unless I'm missing something, I *think* class constructors are the only new ES6 feature where a prologue would be useful/usable.  Can you think of any place else where this would be useful?  

Class methods come to mind, but is there an actual use-case for that?

**Comment by mgol** [comment]
I'd expect it to be used only for class constructors, at least I don't see use cases for annotating methods. If some come up, it can always be added later, I guess. :)
