### ISSUE TITLE
Support for @ngInject within JSDoc blocks

### ISSUE THREAD

**Issue by kamilbrk** [schmod/babel-plugin-angularjs-annotate#31]
Hi,

I was wondering if there's any chance you could consider supporting JSDoc/NGDoc multiline comments with explicit `@ngInject` annotation:

```
  /**
   * Example
   * @someannotation
   * @ngInject
   */
  class svc {}
```

I've made a simple pull request but I'm quite overwhelmed with tests, made just one for ES2015 code. Submitting shortly.

**Comment by schmod** [comment]
I'll take a look at the PR -- this seems like something we can add pretty easily.  However, I want to emphasize that prologue directives are (by far) the most reliable way to add annotations.  

Docblock comments occasionally get moved around by other transformations/preprocessors, and there aren't really any standards that say that they _shouldn't_.  Prologue directives, on the other hand, have an explicit definition in the ECMAScript specification, and tend to be respected by other transformations.

**Comment by kamilbrk** [comment]
Fixed by https://github.com/schmod/babel-plugin-angularjs-annotate/pull/37
