### ISSUE TITLE
Remove prologue string?

### ISSUE THREAD

**Issue by bhollis** [schmod/babel-plugin-angularjs-annotate#38]
I use the 'ngInject' prologue string everywhere, and angularjs-annotate does a wonderful job with it. But once the transform has happened, do we still need that prologue? We could save a bit of space in the final bundle by removing it.

**Comment by schmod** [comment]
Seems like a perfectly reasonable addition, given that a good minifier probably _shouldn't_ be removing those prologue strings.  I don't have a ton of time to work on this project lately, but would be happy to look over a PR, or might be able to get around to looking at this in a few weeks.
