### ISSUE TITLE
babel 7 support

### ISSUE THREAD

**Issue by jakewhelan** [schmod/babel-plugin-angularjs-annotate#42]
I'm currently modernising an angular 1.5 app

I would like to use babel 7 but this plugin has not been updated, are there any plans for this update?

**Comment by schmod** [comment]
@p3x-robot This repo is maintained. Please feel free to open a PR if you'd like to fix this.

**Comment by StabbarN** [comment]
I use this plugin together with babel 7 without any problems.

**Comment by pioug** [comment]
I created a PR https://github.com/schmod/babel-plugin-angularjs-annotate/pull/43. I am not very sure of my changes since I don't follow closely the evolution of Babel but tests are passing 🙏

**Comment by jakewhelan** [comment]
Thanks for arousing my interest @StabbarN, I've since discovered this indeed works with Babel 7 - you just need to require it rather than using the string literal reference as instructed in the README.

```js
module.exports = {
  presets: [
    '@babel/preset-env'
  ],
  plugins: [
    require('babel-plugin-angularjs-annotate'),
    'proposal-optional-chaining'
  ]
```

Though now that I think about it, this should also work just fine:
```js
module.exports = {
  presets: [
    '@babel/preset-env'
  ],
  plugins: [
    'angularjs-annotate',
    'proposal-optional-chaining'
  ]
```

I think all the package naming changes just threw me off.
