### ISSUE TITLE
The babel package shouldn't be a dependency

### ISSUE THREAD

**Issue by mgol** [schmod/babel-plugin-angularjs-annotate#6]
Currently this plugin has the `babel` package as a dependency and it shouldn't. Plugin packages may declare the packages they need to work in `peerDependencies` or not declare at all since it's important that all plugins use the same package and not their own copies.

Other Babel plugins don't include `babel` as a dependency.

**Comment by schmod** [comment]
That looks correct.  I'll fix this in the next release (feel free to submit a PR).

**Comment by mgol** [comment]
Thanks! Sorry I didn't get to it.
